# Generated by Django 4.2.7 on 2025-07-31 17:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('channel', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('lun', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('vendor_identification', models.CharField(max_length=50)),
                ('product_identification', models.CharField(max_length=100)),
                ('product_revision', models.CharField(default='1068', max_length=20)),
                ('unit_serial_number', models.CharField(max_length=50)),
                ('naa', models.CharField(help_text='Network Address Authority', max_length=100)),
                ('home_directory', models.CharField(default='/opt/mhvtl', max_length=255)),
                ('media_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15000)])),
                ('empty_slots', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_standard_config', models.BooleanField(default=True, help_text='True for standard, False for custom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['library_id'],
            },
        ),
        migrations.CreateModel(
            name='LibraryBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('color_code', models.CharField(default='#000000', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LibraryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('CREATE', 'Library Created'), ('UPDATE', 'Library Updated'), ('DELETE', 'Library Deleted'), ('IMPORT', 'Media Imported'), ('EXPORT', 'Media Exported'), ('MOVE', 'Media Moved'), ('MOUNT', 'Media Mounted'), ('UNMOUNT', 'Media Unmounted')], max_length=20)),
                ('description', models.TextField()),
                ('user_session', models.CharField(help_text='Session ID of user', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_slot', models.IntegerField(blank=True, null=True)),
                ('target_slot', models.IntegerField(blank=True, null=True)),
                ('media_barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='libraries.library')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LibraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_identification', models.CharField(max_length=100)),
                ('default_revision', models.CharField(default='1068', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='libraries.librarybrand')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='library',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.librarybrand'),
        ),
        migrations.AddField(
            model_name='library',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.librarymodel'),
        ),
        migrations.CreateModel(
            name='MediaSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('is_empty', models.BooleanField(default=True)),
                ('media_barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('media_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_import_export', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='libraries.library')),
            ],
            options={
                'ordering': ['library', 'slot_number'],
                'unique_together': {('library', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_id', models.IntegerField()),
                ('channel', models.IntegerField()),
                ('target', models.IntegerField()),
                ('lun', models.IntegerField(default=0)),
                ('vendor_identification', models.CharField(max_length=50)),
                ('product_identification', models.CharField(max_length=100)),
                ('product_revision', models.CharField(max_length=20)),
                ('unit_serial_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='libraries.library')),
            ],
            options={
                'ordering': ['library', 'drive_id'],
                'unique_together': {('library', 'drive_id')},
            },
        ),
    ]
