# Generated by Django 4.2.7 on 2025-08-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='config_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drive',
            name='discovery_status',
            field=models.CharField(choices=[('discovered', 'Discovered from MHVTL'), ('created', 'Created in Django'), ('synced', 'Synchronized')], default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='drive',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drive',
            name='mhvtl_id',
            field=models.CharField(blank=True, help_text='Original MHVTL drive identifier', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='config_source',
            field=models.CharField(blank=True, help_text="Source file path (e.g., /etc/mhvtl/device.conf) or 'django-generated'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='discovery_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata from discovery process'),
        ),
        migrations.AddField(
            model_name='library',
            name='discovery_status',
            field=models.CharField(choices=[('discovered', 'Discovered from MHVTL'), ('created', 'Created in Django'), ('synced', 'Synchronized'), ('conflict', 'Sync Conflict')], default='created', help_text='Track how this library was created or discovered', max_length=20),
        ),
        migrations.AddField(
            model_name='library',
            name='last_synced',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful sync with MHVTL files', null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='mhvtl_id',
            field=models.CharField(blank=True, help_text='Original MHVTL library identifier from device.conf', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='sync_hash',
            field=models.CharField(blank=True, help_text='MD5 hash of configuration for change detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='libraryoperation',
            name='discovery_session_id',
            field=models.CharField(blank=True, help_text='Discovery session identifier for tracking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mediaslot',
            name='config_source',
            field=models.CharField(blank=True, help_text='Source file (e.g., library_contents.10)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mediaslot',
            name='discovery_status',
            field=models.CharField(choices=[('discovered', 'Discovered from MHVTL'), ('created', 'Created in Django'), ('synced', 'Synchronized')], default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='mediaslot',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libraryoperation',
            name='operation',
            field=models.CharField(choices=[('CREATE', 'Library Created'), ('UPDATE', 'Library Updated'), ('DELETE', 'Library Deleted'), ('IMPORT', 'Media Imported'), ('EXPORT', 'Media Exported'), ('MOVE', 'Media Moved'), ('MOUNT', 'Media Mounted'), ('UNMOUNT', 'Media Unmounted'), ('DISCOVER', 'Discovery Scan'), ('SYNC', 'File Synchronization')], max_length=20),
        ),
    ]
